import os.path

NAME_YADISK_RESULT_DIR = "PD-142"
NAME_YADISK_RESERVE_CAT_DIR = "CATS"
NAME_YADISK_RESERVE_DOG_DIR = "DOGS"

PATH_TO_RESULTS = r".\results"

PATH_TO_SIZE_CAT_PHOTOS_INFO_DIR = os.path.join(PATH_TO_RESULTS, "cats")
PATH_TO_SIZE_DOG_PHOTOS_INFO_DIR = os.path.join(PATH_TO_RESULTS, "dogs")